services:
  mmdetection3d:
    image: mmdetection3d
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - DISPLAY=$DISPLAY
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=display,compute,utility
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
      - ..:/mmdetection3d
    network_mode: "host"
    working_dir: /mmdetection3d
    deploy:
      resources:
        reservations:
          devices: # 'devices' was unexpected in ubuntu 18.04 default version of docker
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
